version: 0.2

phases:
  install:
    commands:
      - echo Installing SAST tool on `date`
      - npm install snyk@latest -g
      - echo Installing SAST tool completed on `date`
  build:
    commands:
      - echo Building started on `date`
      - snyk auth <YOUR_SNYK_TOKEN>
      - snyk code test
      - echo Building completed on `date`